// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDstHSBMA-Kpr1E-0N2ZR9zVyiVxB-GJTE',
    appId: '1:212031778199:web:3ff74fdf190e999ac5a8d2',
    messagingSenderId: '212031778199',
    projectId: 'rightfitmeasure',
    authDomain: 'rightfitmeasure.firebaseapp.com',
    storageBucket: 'rightfitmeasure.appspot.com',
    measurementId: 'G-00XT1YSM88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCyVlZdLrlqE5hGGZr1qbZJz65rZXbTw0',
    appId: '1:212031778199:android:95ff1ab99211a371c5a8d2',
    messagingSenderId: '212031778199',
    projectId: 'rightfitmeasure',
    storageBucket: 'rightfitmeasure.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh7LxVL0cc0E9jeS8XhBIkDgRNWc-8n3M',
    appId: '1:212031778199:ios:457f16f4f1843c86c5a8d2',
    messagingSenderId: '212031778199',
    projectId: 'rightfitmeasure',
    storageBucket: 'rightfitmeasure.appspot.com',
    iosClientId: '212031778199-oi7smdgti51m7pqjnqm7cqrviarahsvb.apps.googleusercontent.com',
    iosBundleId: 'com.example.bodyMeasurement',
  );
}
